### ISSUE TITLE
suggestions for name

### ISSUE THREAD

**Issue by szbnwer** [n1trux/hestia#3]
what about virtue or vector? - some connection with the origin if it won't stay temporary, and an initial V is good because of the s#!tload of v- and v_ prefixes allaround can stay without frustration :D 

probably vector is too mainstream and can make mess, but virtue have good meanings and VIRT as virtual hosts can be a bit impressive and intuitive

**Comment by n1trux** [comment]
I chose Hestia because [Vesta](https://en.wikipedia.org/wiki/Vesta_(mythology)) was the Roman goddess of the hearth, home, and family and Hestia is the Greek version of her ;)

It's like, if we just called the same software by a different name. I guess virtue or vector are already names quite often in software development.

Don't think we should overthink this one, a name change is rather easy later on. Feel free to discuss this further here, but I'll close this as it's not really an Issue imho ;)

**Comment by szbnwer** [comment]
fine
